import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
import { dark } from "@clerk/themes";
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider appearance={{baseTheme: dark}}>
      <html lang="en">
        <body>
          <ClerkLoading>
            <div className="flex items-center justify-center h-screen text-2xl">
              loading...
            </div>
          </ClerkLoading>
          <ClerkLoaded>
            <div className="max-w-6xl mx-auto">
              <div className="flex flex-col h-screen">
                <main><Navbar/>{children}</main>
              </div>
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
